### ISSUE TITLE
Using a new navigation framework

### ISSUE THREAD

**Issue by juanignaciomolina** [Wolox/wolmo-core-android#28]
# Using a new navigation framework

We should start considering adding to Wolmo a new navigation framework to make development easier.

Some options to consider:
* https://github.com/wealthfront/magellan
* https://github.com/terrakok/Cicerone
* https://github.com/lyft/scoop
* https://github.com/nekocode/Meepo

Personally, I like Magellan's simplicity, but Meepo's approach seems nice as well.

**Comment by emalamela** [comment]
I like the idea!

Some thoughts about what i believe we should consider before adding one:

* Embrace an **Activity per flow - Multiple Fragments** or a **Single Activity - Multiple Views** architecture. **Fragment per flow - Multiple Fragments** is somewhat a middle ground but i dislike it because of the heavy usage of `FragmentManager` which i openly hate.
    * In the first case, each `Activity` is considered an entry point and a flow may be composed by other flows by launching different `Activities`. It integrates easier with our existing workflow and Android in general, but it's harder to test. I would favor `Meepo` for this approach.
    * In the second case, everything is a `View` and the entry points are a custom `Object` (for example a `Screen`). More lightweight and flows can be composed by going to different `Screen`s. If going with this approach, we should use a library. Which has a downside losing some control but gaining testability and having some problems solved by it. I would favor `Magellan` for this approach.
* Have a simple yet robust API to work with.
* History management (ie: going back to a previous point and modifying the history)
* Support customized transitions.
* Be easy to test.
* Be prepared for deep-linking.
* And last but not least, do we want a framework or a library? When thinking about the answer, we should take into account how would including anything would affect `Wolmo` and our current workflow.

With that in mind, some thoughts about each library:

* **Magellan**: I actually love this framework. Minimalist, easy to use and solves some problems inherent to android development (state retention). The downsides i can think of are the fact that it doesn't support `Fragment`s, which is only an issue because some of the libraries we use are deeply tied to them, and the fact that it's not routing-oriented (like `Meepo`). Lastly, it's easy to mock for testing and it's also backed by a lead dev of an important company which is a nice plus. 
* **Cicerone**: Similar to Magellan. What Cicerone has in contrast to it is that Cicerone doesn't hide as much the Android specific stuff, which can be considered good or bad depending on how much abstraction one does want. I don't find it as elegant and don't believe it has a clear advantage over its competitors. Another difference is that it's more lightweight and it's actually a library not a framework.
* **Scoop**: Backed by Lyft which is a big company, this is a full-blown framework. I actually am a fan of the `Scope` concept (hence, it's name) but i believe it's too intrusive. Plus, the scope problem i'm interested in solving is regarding dependency management, which `Dagger` already does.
* **Meepo**: I like the library. The fact that it's philosophy is to be *similar to Retrofit* is awesome. Plus, it's approach is routed-oriented, which is more flexible and even allows easier deep linking. It integrates with Android UI and navigation elements and has some really nice annotations for what is already to boilersome (stuff like adding things to a `Bundle`). I can't see a single heavy downside, the only exigent one i can think of is the the fact that it's not that `Kotlin` friendly (favors annotations instead of DSLs).

Having written all of this, i think the biggest issue is whether we want a framework or not. 

From the top of my head, i would like one and if i had to choose it would be `Magellan`. I believe we could greatly benefit from the problems it solves. It changes the work paradigm but it's so simple and easy that we can quickly forget about `Fragment`s and its quirks. And a big plus, that @alvarez-fabian will love, it's that the `Screen` object it provides is easy to mock and test. The heavy downside is that, in the state that it is now, we would lose some of the advantages `Wolmo` was offering. We could make it work for us with some not-so-big modifications.

On the other hand, if we where to choose a library, i'd use `Meepo`. Even easier that `Magellan` and we can adapt quicker to it. As i said, i can't find a clear weakness to it.

What are you thoughts guys?

**Comment by emalamela** [comment]
@alvarez-fabian @DemianIac I summon you!

**Comment by emalamela** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wolmo: Extraer código para el manejo de navegación](https://trello.com/c/uHRsKoVe/7-wolmo-extraer-c%C3%B3digo-para-el-manejo-de-navegaci%C3%B3n)

**Comment by alvarez-fabian** [comment]
We are currently testing the [Navigation Architecture Component](https://developer.android.com/topic/libraries/architecture/navigation/) with @lmiotti to check if it's worth using. If not we agreed to go with `Meepo` for wolmo.
We'll test it in `WoloxAndroidBootstrap` and then backport the changes here when we finish testing it.
